local addonName, addon = ...

addon.groupieListingTable = {}

addon.groupieLocaleTable = {
    ["frFR"] = "French",
    ["deDE"] = "German",
    ["enGB"] = "English",
    ["enUS"] = "English",
    ["itIT"] = "Italian",
    ["koKR"] = "Korean",
    ["zhCN"] = "Chinese",
    ["zhTW"] = "Chinese",
    ["ruRU"] = "Russian",
    ["esES"] = "Spanish",
    ["esMX"] = "Spanish",
    ["ptBR"] = "Portuguese",
}

addon.groupieRoleTable = {
    [1] = "Tank",
    [2] = "Healer",
    [3] = "Ranged DPS",
    [4] = "Melee DPS"
}

addon.groupieClassRoleTable = {
    ["Death Knight"] = {
        ["Blood"] = { 1 },
        ["Frost"] = { 1, 4 },
        ["Unholy"] = { 4 }
    },
    ["Druid"] = {
        ["Balance"] = { 3 },
        ["Feral Combat"] = { 1, 4 },
        ["Restoration"] = { 2 }
    },
    ["Hunter"] = {
        ["Beast Mastery"] = { 3 },
        ["Marksmanship"] = { 3 },
        ["Survival"] = { 3 }
    },
    ["Mage"] = {
        ["Arcane"] = {},
        ["Fire"] = {},
        ["Frost"] = {}
    },
    ["Paladin"] = {
        ["Holy"] = { 2 },
        ["Protection"] = { 1 },
        ["Retribution"] = { 4 }
    },
    ["Priest"] = {
        ["Discipline"] = { 2 },
        ["Holy"] = { 2 },
        ["Shadow"] = { 3 }
    },
    ["Rogue"] = {
        ["Assassination"] = { 4 },
        ["Combat"] = { 4 },
        ["Subtlety"] = { 4 }
    },
    ["Shaman"] = {
        ["Elemental"] = { 3 },
        ["Enhancement"] = { 4 },
        ["Restoration"] = { 2 }
    },
    ["Warlock"] = {
        ["Affliction"] = { 3 },
        ["Demonology"] = { 3 },
        ["Destruction"] = { 3 }
    },
    ["Warrior"] = {
        ["Arms"] = { 4 },
        ["Fury"] = { 4 },
        ["Protection"] = { 1 }
    }
}


--0 - Heroic
--1 - 10 Normal
--2 - 25 Normal
--3 - Heroic 10
--4 - Heroic 25
addon.groupieVersionPatterns = {
    ["h"] = 0,
    ["hc"] = 0,
    ["heroic"] = 0,
    ["10"] = 1,
    ["n10"] = 1,
    ["10n"] = 1,
    ["25"] = 2,
    ["n25"] = 2,
    ["25n"] = 2,
    ["h10"] = 3,
    ["10h"] = 3,
    ["h25"] = 4,
    ["25h"] = 4
}

--0 - Generic group
--1 - Looking for Tank
--2 - Looking for Healer
--3 - Looking for DPS
--4 - LFG
--5 - boost runs
addon.groupieLFPatterns = {
    ["group"] = 0,
    ["lf"] = 0,
    ["lfm"] = 0,
    ["run"] = 0,
    ["runs"] = 0,
    ["running"] = 0,

    ["lftank"] = 1,
    ["tank"] = 1,
    ["xtank"] = 1,

    ["lfheal"] = 2,
    ["lfhealer"] = 2,
    ["heal"] = 2,
    ["healer"] = 2,
    ["xheal"] = 2,
    ["xhealer"] = 2,

    ["lfdps"] = 3,
    ["lfdd"] = 3,
    ["dps"] = 3,
    ["dd"] = 3,
    ["xdps"] = 3,
    ["xdd"] = 3,

    ["lfg"] = 4,

    ["boost"] = 5,
    ["boosts"] = 5,
    ["boosting"] = 5,
    ["wts"] = 5,
    ["carry"] = 5
}

addon.groupieUnflippedLootPatterns = {
    ["Ticket"] = "ticket",
    ["GDKP"] = "gdkp",
    ["Soft Reserve"] = "sr softres softreserve soft",
    ["MS>OS"] = "msos ms>os ms os"
}

--For now, this only supports English, but implemented such that localization would be easy in the future
addon.groupieUnflippedLanguagePatterns = {
    ["English"] = "english eng",
}

addon.groupieDelimiters = { "%-", ":", ",", "%?", "!", "%." }

addon.multiWingInstances = { "Dire Maul - Full Clear", "Maraudon - Full Clear", "Scarlet Monastery - Full Clear" }

--instanceVersions[instance] = {{size, isHeroic}, ...}
addon.instanceVersions = {
    ["Ragefire Chasm"]                 = { { 5, false } },
    ["Wailing Caverns"]                = { { 5, false } },
    ["The Deadmines"]                  = { { 5, false } },
    ["Shadowfang Keep"]                = { { 5, false } },
    ["The Stockade"]                   = { { 5, false } },
    ["Blackfathom Deeps"]              = { { 5, false } },
    ["Gnomeregan"]                     = { { 5, false } },
    ["Razorfen Kraul"]                 = { { 5, false } },
    ["Scarlet Monastery - Full Clear"] = { { 5, false } },
    ["Scarlet Monastery - Graveyard"]  = { { 5, false } },
    ["Scarlet Monastery - Library"]    = { { 5, false } },
    ["Scarlet Monastery - Armory"]     = { { 5, false } },
    ["Scarlet Monastery - Cathedral"]  = { { 5, false } },
    ["Razorfen Downs"]                 = { { 5, false } },
    ["Uldaman"]                        = { { 5, false } },
    ["Zul'Farrak"]                     = { { 5, false } },
    ["Maraudon - Full Clear"]          = { { 5, false } },
    ["Maraudon - Princess"]            = { { 5, false } },
    ["Maraudon - Purple"]              = { { 5, false } },
    ["Maraudon - Orange"]              = { { 5, false } },
    ["The Temple of Atal'Hakkar"]      = { { 5, false } },
    ["Blackrock Depths"]               = { { 5, false } },
    ["Dire Maul - Full Clear"]         = { { 5, false } },
    ["Dire Maul - East Wing"]          = { { 5, false } },
    ["Dire Maul - North Wing"]         = { { 5, false } },
    ["Dire Maul - West Wing"]          = { { 5, false } },
    ["Lower Blackrock Spire"]          = { { 5, false } },
    ["Stratholme"]                     = { { 5, false } },
    ["Scholomance"]                    = { { 5, false } },

    ["Upper Blackrock Spire"] = { { 10, false } },
    ["Zul'Gurub"]             = { { 20, false } },
    ["Ruins of Ahn'Qiraj"]    = { { 20, false } },
    ["Onyxia's Lair"]         = { { 40, false } },
    ["Molten Core"]           = { { 40, false } },
    ["Blackwing Lair"]        = { { 40, false } },
    ["Temple of Ahn'Qiraj"]   = { { 40, false } },
    --["Naxxramas"]             = { { 40, false } },

    ["Hellfire Ramparts"]       = { { 5, false }, { 5, true } },
    ["The Blood Furnace"]       = { { 5, false }, { 5, true } },
    ["The Slave Pens"]          = { { 5, false }, { 5, true } },
    ["The Underbog"]            = { { 5, false }, { 5, true } },
    ["Mana-Tombs"]              = { { 5, false }, { 5, true } },
    ["Auchenai Crypts"]         = { { 5, false }, { 5, true } },
    ["Sethekk Halls"]           = { { 5, false }, { 5, true } },
    ["Old Hillsbrad Foothills"] = { { 5, false }, { 5, true } },
    ["Shadow Labyrinth"]        = { { 5, false }, { 5, true } },
    ["The Mechanar"]            = { { 5, false }, { 5, true } },
    ["The Shattered Halls"]     = { { 5, false }, { 5, true } },
    ["The Steamvault"]          = { { 5, false }, { 5, true } },
    ["The Botanica"]            = { { 5, false }, { 5, true } },
    ["The Arcatraz"]            = { { 5, false }, { 5, true } },
    ["The Black Morass"]        = { { 5, false }, { 5, true } },
    ["Magisters' Terrace"]      = { { 5, false }, { 5, true } },

    ["Karazhan"]             = { { 10, false } },
    ["Zul'Aman"]             = { { 10, false } },
    ["Gruul's Lair"]         = { { 25, false } },
    ["Magtheridon's Lair"]   = { { 25, false } },
    ["Serpentshrine Cavern"] = { { 25, false } },
    ["The Eye"]              = { { 25, false } },
    ["Hyjal Summit"]         = { { 25, false } },
    ["Black Temple"]         = { { 25, false } },
    ["Sunwell Plateau"]      = { { 25, false } },

    ["Utgarde Keep"]               = { { 5, false }, { 5, true } },
    ["Nexus"]                      = { { 5, false }, { 5, true } },
    ["Ajzol-Nerub"]                = { { 5, false }, { 5, true } },
    ["Ahn'kahet: The Old Kingdom"] = { { 5, false }, { 5, true } },
    ["Drak'Tharon Keep"]           = { { 5, false }, { 5, true } },
    ["Violet Hold"]                = { { 5, false }, { 5, true } },
    ["Gundrak"]                    = { { 5, false }, { 5, true } },
    ["Halls of Stone"]             = { { 5, false }, { 5, true } },
    ["The Culling of Stratholme"]  = { { 5, false }, { 5, true } },
    ["Halls of Lightning"]         = { { 5, false }, { 5, true } },
    ["Utgarde Pinnacle"]           = { { 5, false }, { 5, true } },
    ["The Oculus"]                 = { { 5, false }, { 5, true } },
    ["Trial of the Champion"]      = { { 5, false }, { 5, true } },
    ["Forge of Souls"]             = { { 5, false }, { 5, true } },
    ["Pit of Saron"]               = { { 5, false }, { 5, true } },
    ["Halls of Reflection"]        = { { 5, false }, { 5, true } },

    ["Naxxramas"]            = { { 10, false }, { 25, false } },
    ["The Obsidian Sanctum"] = { { 10, false }, { 25, false } },
    ["Vault of Archavon"]    = { { 10, false }, { 25, false } },
    ["The Eye of Eternity"]  = { { 10, false }, { 25, false } },
    --["Onyxia's Lair"]        = { { 10, false }, { 25, false } },
    ["Ulduar"]               = { { 10, false }, { 25, false } },

    ["Crusaders' Coliseum: Trial of the Crusader"] = { { 10, false }, { 25, false }, { 10, true }, { 25, true } },
    ["Icecrown Citadel"]                           = { { 10, false }, { 25, false }, { 10, true }, { 25, true } },
    ["The Ruby Sanctum"]                           = { { 10, false }, { 25, false }, { 10, true }, { 25, true } },

    ["Brewfest"]     = { { 5, false } },
    ["Hallow's End"] = { { 5, false } },
}

addon.groupieInstanceData = {
    ["Heroic The Ruby Sanctum - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 2550 },
    ["Heroic Icecrown Citadel - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 2540 },
    ["Heroic Crusaders' Coliseum: Trial of the Crusader - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 2530 },
    ["Heroic The Ruby Sanctum - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 2520 },
    ["Heroic Icecrown Citadel - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 2510 },
    ["Heroic Crusaders' Coliseum: Trial of the Crusader - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Heroic Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 2500 },
    ["The Ruby Sanctum - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2490 },
    ["Icecrown Citadel - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2480 },
    ["Crusaders' Coliseum: Trial of the Crusader - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2470 },
    ["Ulduar - 25"] = { Active = false, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich - 25 Raids",
        InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25, Order = 2460 },
    ["Onyxia's Lair - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2450 },
    ["The Eye of Eternity - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2440 },
    ["Vault of Archavon - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2430 },
    ["The Obsidian Sanctum - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 25 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25,
        Order = 2420 },
    ["Naxxramas - 25"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich - 25 Raids",
        InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 25, Order = 2410 },
    ["The Ruby Sanctum - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2400 },
    ["Icecrown Citadel - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2390 },
    ["Crusaders' Coliseum: Trial of the Crusader - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2380 },
    ["Ulduar - 10"] = { Active = false, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich - 10 Raids",
        InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10, Order = 2370 },
    ["Onyxia's Lair - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2360 },
    ["The Eye of Eternity - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2350 },
    ["Vault of Archavon - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2340 },
    ["The Obsidian Sanctum - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich - 10 Raids", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10,
        Order = 2330 },
    ["Naxxramas - 10"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich - 10 Raids",
        InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 10, Order = 2320 },
    ["Heroic Ahn'kahet: The Old Kingdom"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2310 },
    ["Heroic Ajzol-Nerub"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2300 },
    ["Heroic Drak'Tharon Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2290 },
    ["Heroic Forge of Souls"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2280 },
    ["Heroic Gundrak"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2270 },
    ["Heroic Halls of Lightning"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2260 },
    ["Heroic Halls of Reflection"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2250 },
    ["Heroic Halls of Stone"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2240 },
    ["Heroic Nexus"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2230 },
    ["Heroic Pit of Saron"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2220 },
    ["Heroic The Culling of Stratholme"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2210 },
    ["Heroic The Oculus"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2200 },
    ["Heroic Trial of the Champion"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2190 },
    ["Heroic Utgarde Pinnacle"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2180 },
    ["Heroic Violet Hold"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2170 },
    ["Heroic Utgarde Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 2160 },
    ["Halls of Reflection"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 5,
        Order = 2150 },
    ["Pit of Saron"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 5,
        Order = 2140 },
    ["Forge of Souls"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 5,
        Order = 2130 },
    ["Trial of the Champion"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 80, MaxLevel = 80, GroupSize = 5,
        Order = 2120 },
    ["The Oculus"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 79, MaxLevel = 80, GroupSize = 5, Order = 2110 },
    ["Utgarde Pinnacle"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 79, MaxLevel = 80, GroupSize = 5,
        Order = 2100 },
    ["Halls of Lightning"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 2090 },
    ["The Culling of Stratholme"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 2080 },
    ["Halls of Stone"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 77, MaxLevel = 79, GroupSize = 5,
        Order = 2070 },
    ["Gundrak"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 76, MaxLevel = 78, GroupSize = 5, Order = 2060 },
    ["Violet Hold"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 75, MaxLevel = 77, GroupSize = 5, Order = 2050 },
    ["Drak'Tharon Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 74, MaxLevel = 76, GroupSize = 5,
        Order = 2040 },
    ["Ahn'kahet: The Old Kingdom"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 73, MaxLevel = 75, GroupSize = 5,
        Order = 2030 },
    ["Ajzol-Nerub"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 72, MaxLevel = 74, GroupSize = 5, Order = 2020 },
    ["Nexus"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 69, MaxLevel = 73, GroupSize = 5, Order = 2010 },
    ["Utgarde Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 69, MaxLevel = 72, GroupSize = 5,
        Order = 2000 },
    ["Sunwell Plateau"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 5, Order = 1400 },
    ["Black Temple"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1390 },
    ["Hyjal Summit"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1380 },
    ["The Eye"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1370 },
    ["Serpentshrine Cavern"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1360 },
    ["Magtheridon's Lair"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1350 },
    ["Gruul's Lair"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 1340 },
    ["Zul'Aman"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 10, Order = 1330 },
    ["Karazhan"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = -1, MinLevel = 70, MaxLevel = 70, GroupSize = 10, Order = 1320 },
    ["Heroic Auchenai Crypts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1310 },
    ["Heroic Hellfire Ramparts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1300 },
    ["Heroic Magisters' Terrace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1290 },
    ["Heroic Mana-Tombs"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1280 },
    ["Heroic Old Hillsbrad Foothills"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1270 },
    ["Heroic Sethekk Halls"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1260 },
    ["Heroic Shadow Labyrinth"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1250 },
    ["Heroic The Arcatraz"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1240 },
    ["Heroic The Black Morass"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1230 },
    ["Heroic The Blood Furnace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1220 },
    ["Heroic The Botanica"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1210 },
    ["Heroic The Mechanar"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1200 },
    ["Heroic The Shattered Halls"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1190 },
    ["Heroic The Slave Pens"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1180 },
    ["Heroic The Steamvault"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1170 },
    ["Heroic The Underbog"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = -1, MinLevel = 70, MaxLevel = 70,
        GroupSize = 5, Order = 1160 },
    ["Magisters' Terrace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5,
        Order = 1150 },
    ["The Black Morass"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5,
        Order = 1140 },
    ["The Arcatraz"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5, Order = 1130 },
    ["The Botanica"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5, Order = 1120 },
    ["The Steamvault"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5, Order = 1110 },
    ["The Shattered Halls"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 69, MaxLevel = 70, GroupSize = 5,
        Order = 1100 },
    ["The Mechanar"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 68, MaxLevel = 70, GroupSize = 5, Order = 1090 },
    ["Shadow Labyrinth"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 68, MaxLevel = 70, GroupSize = 5,
        Order = 1080 },
    ["Old Hillsbrad Foothills"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 66, MaxLevel = 70, GroupSize = 5,
        Order = 1070 },
    ["Sethekk Halls"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 66, MaxLevel = 70, GroupSize = 5, Order = 1060 },
    ["Auchenai Crypts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 64, MaxLevel = 70, GroupSize = 5,
        Order = 1050 },
    ["Mana-Tombs"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 63, MaxLevel = 70, GroupSize = 5, Order = 1040 },
    ["The Underbog"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 62, MaxLevel = 70, GroupSize = 5, Order = 1030 },
    ["The Slave Pens"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = -1, MinLevel = 61, MaxLevel = 69, GroupSize = 5, Order = 1020 },
    ["The Blood Furnace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 60, MaxLevel = 68, GroupSize = 5,
        Order = 1010 },
    ["Hellfire Ramparts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = -1, MinLevel = 59, MaxLevel = 67, GroupSize = 5,
        Order = 1000 },
    ["Naxxramas"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = -1,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 370 },
    ["Temple of Ahn'Qiraj"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = -1, MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 360 },
    ["Blackwing Lair"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = -1,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 350 },
    ["Molten Core"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = -1,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 340 },
    ["Onyxia's Lair"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = -1,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 330 },
    ["Ruins of Ahn'Qiraj"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = -1, MinLevel = 60, MaxLevel = 60, GroupSize = 20, Order = 320 },
    ["Zul'Gurub"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = -1,
        MinLevel = 60, MaxLevel = 60, GroupSize = 20, Order = 310 },
    ["Upper Blackrock Spire"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = -1, MinLevel = 60, MaxLevel = 60, GroupSize = 10, Order = 300 },
    ["Stratholme"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 58, MaxLevel = 60, GroupSize = 5, Order = 290 },
    ["Scholomance"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 58, MaxLevel = 60, GroupSize = 5, Order = 280 },
    ["Lower Blackrock Spire"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 55, MaxLevel = 60, GroupSize = 5, Order = 270 },
    ["Dire Maul - Full Clear"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 54, MaxLevel = 60, GroupSize = 5, Order = 260 },
    ["Dire Maul - North Wing"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 58, MaxLevel = 60, GroupSize = 5, Order = 250 },
    ["Dire Maul - West Wing"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 56, MaxLevel = 60, GroupSize = 5, Order = 240 },
    ["Dire Maul - East Wing"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 54, MaxLevel = 60, GroupSize = 5, Order = 230 },
    ["Blackrock Depths"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 52, MaxLevel = 60, GroupSize = 5, Order = 220 },
    ["The Temple of Atal'Hakkar"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 50, MaxLevel = 60, GroupSize = 5, Order = 210 },
    ["Maraudon - Full Clear"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 45, MaxLevel = 57, GroupSize = 5, Order = 200 },
    ["Maraudon - Princess"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 48, MaxLevel = 57, GroupSize = 5, Order = 190 },
    ["Maraudon - Orange"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 45, MaxLevel = 53, GroupSize = 5, Order = 180 },
    ["Maraudon - Purple"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 45, MaxLevel = 53, GroupSize = 5, Order = 170 },
    ["Zul'Farrak"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 44, MaxLevel = 54, GroupSize = 5, Order = 160 },
    ["Uldaman"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 42, MaxLevel = 52, GroupSize = 5, Order = 150 },
    ["Razorfen Downs"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -
            1, MinLevel = 40, MaxLevel = 50, GroupSize = 5, Order = 140 },
    ["Scarlet Monastery - Full Clear"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 28, MaxLevel = 45, GroupSize = 5, Order = 130 },
    ["Scarlet Monastery - Cathedral"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 35, MaxLevel = 45, GroupSize = 5, Order = 120 },
    ["Scarlet Monastery - Armory"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 32, MaxLevel = 42, GroupSize = 5, Order = 110 },
    ["Scarlet Monastery - Library"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 29, MaxLevel = 39, GroupSize = 5, Order = 100 },
    ["Scarlet Monastery - Graveyard"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 28, MaxLevel = 38, GroupSize = 5, Order = 90 },
    ["Razorfen Kraul"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -
            1, MinLevel = 30, MaxLevel = 40, GroupSize = 5, Order = 80 },
    ["Gnomeregan"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 29, MaxLevel = 38, GroupSize = 5, Order = 70 },
    ["Blackfathom Deeps"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 24, MaxLevel = 32, GroupSize = 5, Order = 60 },
    ["The Stockade"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 22, MaxLevel = 30, GroupSize = 5, Order = 50 },
    ["Shadowfang Keep"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 22, MaxLevel = 30, GroupSize = 5, Order = 40 },
    ["The Deadmines"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = -1,
        MinLevel = 18, MaxLevel = 23, GroupSize = 5, Order = 30 },
    ["Wailing Caverns"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -1, MinLevel = 15, MaxLevel = 25, GroupSize = 5, Order = 20 },
    ["Ragefire Chasm"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = -
            1, MinLevel = 13, MaxLevel = 18, GroupSize = 5, Order = 10 }

}


addon.groupieUnflippedDungeonPatterns = {
    ["Ragefire Chasm"]                 = "rfc ragefire chasm",
    ["Wailing Caverns"]                = "wc wailing caverns",
    ["The Deadmines"]                  = "deadmines vc vancleef dead mines mine",
    ["Shadowfang Keep"]                = "sfk shadowfang",
    ["The Stockade"]                   = "stk stock stockade stockades",
    ["Blackfathom Deeps"]              = "bfd blackfathom fathom",
    ["Gnomeregan"]                     = "gnomer gno gnomeregan gnomeragan gnome gnomregan gnomragan gnom gnomergan",
    ["Razorfen Kraul"]                 = "rfk kraul",
    ["Scarlet Monastery - Full Clear"] = "sm scarlet monastery mona",
    ["Scarlet Monastery - Graveyard"]  = "smgy smg gy graveyard",
    ["Scarlet Monastery - Library"]    = "smlib sml lib library",
    ["Scarlet Monastery - Armory"]     = "smarm sma arm armory herod armoury arms",
    ["Scarlet Monastery - Cathedral"]  = "smcath smc cath cathedral",
    ["Razorfen Downs"]                 = "rfd downs",
    ["Uldaman"]                        = "uld ulda uldaman ulduman uldman uldama udaman",
    ["Zul'Farrak"]                     = "zf zul farrak zul'farrak zulfarrak zulfarak zul´farrak zul`farrak zulfa zulf",
    ["Maraudon - Full Clear"]          = "mar mara maraudon mauradon mauro maurodon maraudin maura marau mauraudon",
    ["Maraudon - Princess"]            = "princessrun princess",
    ["Maraudon - Purple"]              = "marpurp marpurple marapurp marapurple maraudonpurple purple, purp",
    ["Maraudon - Orange"]              = "marorange maraorange maraudonorange orange",
    ["The Temple of Atal'Hakkar"]      = "st sunken atal temple",
    ["Blackrock Depths"]               = "brd emperor emp arenarun angerforge blackrockdepth",
    ["Dire Maul - Full Clear"]         = "dire maul diremaul",
    ["Dire Maul - East Wing"]          = "dme dmeast east puzilin jumprun",
    ["Dire Maul - North Wing"]         = "dmn dmnorth north tribute",
    ["Dire Maul - West Wing"]          = "dmw dmwest west",
    ["Lower Blackrock Spire"]          = "lower lbrs lrbs",
    ["Stratholme"]                     = "stratlive live living stratUD undead ud baron stratholme stath stratholm strah strath strat starth",
    ["Scholomance"]                    = "scholomance scholo sholo sholomance",

    ["Upper Blackrock Spire"] = "upper ubrs urbs rend",
    ["Zul'Gurub"]             = "zg gurub zul'gurub zulgurub zul´gurub zul`gurub zulg zul-gurub",
    ["Ruins of Ahn'Qiraj"]    = "ruins aq20",
    ["Onyxia's Lair"]         = "onyxia ony",
    ["Molten Core"]           = "molten core mc",
    ["Blackwing Lair"]        = "blackwing bwl",
    ["Temple of Ahn'Qiraj"]   = "aq40",
    ["Naxxramas"]             = "naxxramas nax naxx",

    ["Hellfire Ramparts"]       = "ramparts rampart ramp ramps",
    ["The Blood Furnace"]       = "furnace furn bf",
    ["The Slave Pens"]          = "slavepens pens sp",
    ["The Underbog"]            = "underbog ub",
    ["Mana-Tombs"]              = "manatombs mana mt tomb tombs",
    ["Auchenai Crypts"]         = "crypts crypt auchenai ac acrypts acrypt",
    ["Sethekk Halls"]           = "sethekk seth sethek",
    ["Old Hillsbrad Foothills"] = "ohb oh ohf durnholde hillsbrad escape",
    ["Shadow Labyrinth"]        = "sl slab labyrinth lab",
    ["The Mechanar"]            = "mech mechanar",
    ["The Shattered Halls"]     = "sh shattered shatered shaterred",
    ["The Steamvault"]          = "sv steamvault steamvaults steam vault valts",
    ["The Botanica"]            = "botanica bot",
    ["The Arcatraz"]            = "arc arcatraz alcatraz",
    ["The Black Morass"]        = "morass bm black",
    ["Magisters' Terrace"]      = "mgt mrt terrace magisters magister",

    ["Karazhan"]             = "kara kz karazhan",
    ["Zul'Aman"]             = "za zulaman zul-aman zaman aman zul'aman",
    ["Gruul's Lair"]         = "gl gruul gruuls gruul's",
    ["Magtheridon's Lair"]   = "mag magtheridon magtheridon's magth",
    ["Serpentshrine Cavern"] = "ssc serpentshrine serpentshine",
    ["The Eye"]              = "eye tk",
    ["Hyjal Summit"]         = "hyjal hs hyj",
    ["Black Temple"]         = "bt blacktemple",
    ["Sunwell Plateau"]      = "swp sunwell plateau plataeu sunwel",

    ["Brewfest"]     = "brewfest brew coren dire direbrew beerfest",
    ["Hallow's End"] = "headless horseman hollow",
}


addon.groupieInstancePatterns = addon.TableFlip(addon.groupieUnflippedDungeonPatterns)
addon.groupieLootPatterns = addon.TableFlip(addon.groupieUnflippedLootPatterns)
addon.groupieLanguagePatterns = addon.TableFlip(addon.groupieUnflippedLanguagePatterns)
