local addonName, addon = ...
local L = LibStub('AceLocale-3.0'):GetLocale('Groupie')

--This file ONLY contains the table from google sheet for instance data
--Do not put any other data here

--Instance IDs from : https://wowpedia.fandom.com/wiki/InstanceID
addon.groupieInstanceData = {
    ["Heroic Ruby Sanctum - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 25", InstanceID = 724, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3550, ActivityID = 1109, Icon = "RS.tga" },
    ["Heroic Icecrown Citadel - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 25", InstanceID = 631, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3540, ActivityID = 1111, Icon = "ICC.tga" },
    ["Heroic Trial of the Grand Crusader - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 25", InstanceID = 649, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3530, ActivityID = 1105, Icon = "TOC Raid.tga" },
    ["Heroic Ruby Sanctum - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 10", InstanceID = 724, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3520, ActivityID = 1108, Icon = "RS.tga" },
    ["Heroic Icecrown Citadel - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 10", InstanceID = 631, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3510, ActivityID = 1110, Icon = "ICC.tga" },
    ["Heroic Trial of the Grand Crusader - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Raids - 10", InstanceID = 649, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3500, ActivityID = 1103, Icon = "TOC Raid.tga" },
    ["Ruby Sanctum - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 724, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3490, ActivityID = 1109, Icon = "RS.tga" },
    ["Icecrown Citadel - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 631, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3480, ActivityID = 1111, Icon = "ICC.tga" },
    ["Trial of the Crusader - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 649, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3470, ActivityID = 1104, Icon = "TOC Raid.tga" },
    ["Ulduar - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 603, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3460, ActivityID = 1107, Icon = "ULD.tga" },
    ["Onyxia's Lair - 25"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 249, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3450, ActivityID = 1099, Icon = "ONY.tga" },
    ["Eye of Eternity - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 616, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3440, ActivityID = 1094, Icon = "EOE.tga" },
    ["Naxxramas - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 533, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3430, ActivityID = 1098, Icon = "NAX.tga" },
    ["Obsidian Sanctum - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 615, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3420, ActivityID = 1097, Icon = "OS.tga" },
    ["Vault of Archavon - 25"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 25", InstanceID = 624, MinLevel = 80, MaxLevel = 80,
        GroupSize = 25, Order = 3410, ActivityID = 1096, Icon = "VOA.tga" },
    ["Ruby Sanctum - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 724, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3400, ActivityID = 1108, Icon = "RS.tga" },
    ["Icecrown Citadel - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 631, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3390, ActivityID = 1110, Icon = "ICC.tga" },
    ["Trial of the Crusader - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 649, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3380, ActivityID = 1100, Icon = "TOC Raid.tga" },
    ["Ulduar - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 603, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3370, ActivityID = 1106, Icon = "ULD.tga" },
    ["Onyxia's Lair - 10"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 249, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3360, ActivityID = 1156, Icon = "ONY.tga" },
    ["Eye of Eternity - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 616, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3350, ActivityID = 1102, Icon = "EOE.tga" },
    ["Obsidian Sanctum - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 615, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3340, ActivityID = 1101, Icon = "OS.tga" },
    ["Naxxramas - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 533, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3330, ActivityID = 841, Icon = "NAX.tga" },
    ["Vault of Archavon - 10"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Raids - 10", InstanceID = 624, MinLevel = 80, MaxLevel = 80,
        GroupSize = 10, Order = 3320, ActivityID = 1095, Icon = "VOA.tga" },
    ["Heroic Azjol-Nerub"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 601, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3310, ActivityID = 1121, Icon = "AN.tga" },
    ["Heroic Culling of Stratholme"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 595, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3300, ActivityID = 1126, Icon = "COS.tga" },
    ["Heroic Drak'Tharon Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 600, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3290, ActivityID = 1129, Icon = "DTK.tga" },
    ["Heroic Forge of Souls"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 632, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3280, ActivityID = 1134, Icon = "FOS.tga" },
    ["Heroic Gundrak"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 604, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3270, ActivityID = 1130, Icon = "GUN.tga" },
    ["Heroic Halls of Lightning"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 602, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3260, ActivityID = 1127, Icon = "HOL.tga" },
    ["Heroic Halls of Reflection"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 668, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3250, ActivityID = 1136, Icon = "HOR.tga" },
    ["Heroic Halls of Stone"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 599, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3240, ActivityID = 1128, Icon = "HOS.tga" },
    ["Heroic Nexus"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 576, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3230, ActivityID = 1132, Icon = "NEX.tga" },
    ["Heroic Oculus"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 578, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3220, ActivityID = 1124, Icon = "OC.tga" },
    ["Heroic Old Kingdom"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 619, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3210, ActivityID = 1131, Icon = "OK.tga" },
    ["Heroic Pit of Saron"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 658, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3200, ActivityID = 1135, Icon = "PIT.tga" },
    ["Heroic Trial of the Champion"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 650, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3190, ActivityID = 1133, Icon = "TOC Dungeon.tga" },
    ["Heroic Utgarde Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 574, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3180, ActivityID = 1122, Icon = "UK.tga" },
    ["Heroic Utgarde Pinnacle"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 575, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3170, ActivityID = 1125, Icon = "UP.tga" },
    ["Heroic Violet Hold"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Heroic Dungeons", InstanceID = 608, MinLevel = 80, MaxLevel = 80,
        GroupSize = 5, Order = 3160, ActivityID = 1123, Icon = "VH.tga" },
    ["Halls of Reflection"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 668, MinLevel = 80, MaxLevel = 80, GroupSize = 5,
        Order = 3150, ActivityID = 1080, Icon = "HOR.tga" },
    ["Forge of Souls"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 632, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3140, ActivityID = 1078, Icon = "FOS.tga" },
    ["Pit of Saron"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 658, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3130, ActivityID = 1079, Icon = "PIT.tga" },
    ["Trial of the Champion"] = { Active = false, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 650, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3120, ActivityID = 1076, Icon = "TOC Dungeon.tga" },
    ["Culling of Stratholme"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 595, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3110, ActivityID = 1065, Icon = "COS.tga" },
    ["Halls of Lightning"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 602, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3100, ActivityID = 1068, Icon = "HOL.tga" },
    ["Oculus"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 578, MinLevel = 78, MaxLevel = 80, GroupSize = 5, Order = 3090, ActivityID = 1067, Icon = "OC.tga" },
    ["Utgarde Pinnacle"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 575, MinLevel = 78, MaxLevel = 80, GroupSize = 5,
        Order = 3080, ActivityID = 1075, Icon = "UP.tga" },
    ["Gundrak"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 604, MinLevel = 76, MaxLevel = 80, GroupSize = 5, Order = 3070, ActivityID = 1071, Icon = "GUN.tga" },
    ["Halls of Stone"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 599, MinLevel = 75, MaxLevel = 80, GroupSize = 5,
        Order = 3060, ActivityID = 1069, Icon = "HOS.tga" },
    ["Violet Hold"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 608, MinLevel = 73, MaxLevel = 78, GroupSize = 5, Order = 3050, ActivityID = 1073, Icon = "VH.tga" },
    ["Drak'Tharon Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 600, MinLevel = 72, MaxLevel = 78, GroupSize = 5,
        Order = 3040, ActivityID = 1070, Icon = "DTK.tga" },
    ["Old Kingdom"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 619, MinLevel = 71, MaxLevel = 78, GroupSize = 5, Order = 3030, ActivityID = 1072, Icon = "OK.tga" },
    ["Azjol-Nerub"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 601, MinLevel = 70, MaxLevel = 77, GroupSize = 5, Order = 3020, ActivityID = 1066, Icon = "AN.tga" },
    ["Nexus"] = { Active = true, Expac = "Wrath of the Lich King", InstanceType = "Wrath of the Lich King Dungeons",
        InstanceID = 576, MinLevel = 70, MaxLevel = 75, GroupSize = 5, Order = 3010, ActivityID = 1077, Icon = "NEX.tga" },
    ["Utgarde Keep"] = { Active = true, Expac = "Wrath of the Lich King",
        InstanceType = "Wrath of the Lich King Dungeons", InstanceID = 574, MinLevel = 68, MaxLevel = 75, GroupSize = 5,
        Order = 3000, ActivityID = 1074, Icon = "UK.tga" },
    ["Sunwell Plateau"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 580, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2400, ActivityID = 852, Icon = "SWP.tga" },
    ["Black Temple"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 564, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2390, ActivityID = 850, Icon = "BT.tga" },
    ["Mount Hyjal"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 534, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2380, ActivityID = 849, Icon = "MH.tga" },
    ["Tempest Keep"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 550, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2370, ActivityID = 847, Icon = "TK.tga" },
    ["Serpentshrine Cavern"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 548, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2360, ActivityID = 848, Icon = "SSC.tga" },
    ["Magtheridon's Lair"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 544, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2350, ActivityID = 845, Icon = "MAG.tga" },
    ["Gruul's Lair"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 565, MinLevel = 70, MaxLevel = 70, GroupSize = 25, Order = 2340, ActivityID = 846,
        Icon = "GRUUL.tga" },
    ["Zul'Aman"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 568, MinLevel = 70, MaxLevel = 70, GroupSize = 10, Order = 2330, ActivityID = 851, Icon = "ZA.tga" },
    ["Karazhan"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Raids",
        InstanceID = 532, MinLevel = 70, MaxLevel = 70, GroupSize = 10, Order = 2320, ActivityID = 844, Icon = "KARA.tga" },
    ["Heroic Arcatraz"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 552, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2310, ActivityID = 915, Icon = "ARC.tga" },
    ["Heroic Auchenai Crypts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 558, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2300, ActivityID = 903, Icon = "AC.tga" },
    ["Heroic Black Morass"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 269, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2290, ActivityID = 907, Icon = "BM.tga" },
    ["Heroic Blood Furnace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 542, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2280, ActivityID = 912, Icon = "BF.tga" },
    ["Heroic Botanica"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 553, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2270, ActivityID = 918, Icon = "BOT.tga" },
    ["Heroic Hellfire Ramparts"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 543, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2260, ActivityID = 913, Icon = "RAMPS.tga" },
    ["Heroic Magisters' Terrace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 585, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2250, ActivityID = 917, Icon = "MGT.tga" },
    ["Heroic Mana-Tombs"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 557, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2240, ActivityID = 904, Icon = "MT.tga" },
    ["Heroic Mechanar"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 554, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2230, ActivityID = 916, Icon = "MECH.tga" },
    ["Heroic Old Hillsbrad Foothills"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 560, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2220, ActivityID = 908, Icon = "OHB.tga" },
    ["Heroic Sethekk Halls"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 556, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2210, ActivityID = 905, Icon = "SETHEKK.tga" },
    ["Heroic Shadow Labyrinth"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 555, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2200, ActivityID = 906, Icon = "SL.tga" },
    ["Heroic Shattered Halls"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 540, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2190, ActivityID = 914, Icon = "SH.tga" },
    ["Heroic Slave Pens"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 547, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2180, ActivityID = 909, Icon = "SP.tga" },
    ["Heroic Steamvault"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 545, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2170, ActivityID = 910, Icon = "SV.tga" },
    ["Heroic Underbog"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Heroic Dungeons", InstanceID = 546, MinLevel = 70, MaxLevel = 72,
        GroupSize = 5, Order = 2160, ActivityID = 911, Icon = "UB.tga" },
    ["Magisters' Terrace"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Dungeons", InstanceID = 585, MinLevel = 69, MaxLevel = 72, GroupSize = 5,
        Order = 2150, ActivityID = 835, Icon = "MGT.tga" },
    ["Steamvault"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 545, MinLevel = 69, MaxLevel = 72, GroupSize = 5, Order = 2140, ActivityID = 822, Icon = "SV.tga" },
    ["Arcatraz"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 552, MinLevel = 69, MaxLevel = 72, GroupSize = 5, Order = 2130, ActivityID = 834, Icon = "ARC.tga" },
    ["Botanica"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 553, MinLevel = 69, MaxLevel = 75, GroupSize = 5, Order = 2120, ActivityID = 833, Icon = "BOT.tga" },
    ["Shadow Labyrinth"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 555, MinLevel = 69, MaxLevel = 72, GroupSize = 5, Order = 2110, ActivityID = 826, Icon = "SL.tga" },
    ["Shattered Halls"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 540, MinLevel = 69, MaxLevel = 72, GroupSize = 5, Order = 2100, ActivityID = 819, Icon = "SH.tga" },
    ["Black Morass"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 269, MinLevel = 68, MaxLevel = 72, GroupSize = 5, Order = 2090, ActivityID = 831, Icon = "BM.tga" },
    ["Mechanar"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 554, MinLevel = 68, MaxLevel = 72, GroupSize = 5, Order = 2080, ActivityID = 832, Icon = "MECH.tga" },
    ["Sethekk Halls"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 556, MinLevel = 66, MaxLevel = 72, GroupSize = 5, Order = 2070, ActivityID = 825,
        Icon = "SETHEKK.tga" },
    ["Old Hillsbrad Foothills"] = { Active = true, Expac = "The Burning Crusade",
        InstanceType = "The Burning Crusade Dungeons", InstanceID = 560, MinLevel = 66, MaxLevel = 72, GroupSize = 5,
        Order = 2060, ActivityID = 830, Icon = "OHB.tga" },
    ["Auchenai Crypts"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 558, MinLevel = 64, MaxLevel = 72, GroupSize = 5, Order = 2050, ActivityID = 824, Icon = "AC.tga" },
    ["Mana-Tombs"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 557, MinLevel = 63, MaxLevel = 71, GroupSize = 5, Order = 2040, ActivityID = 823, Icon = "MT.tga" },
    ["Underbog"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 546, MinLevel = 62, MaxLevel = 70, GroupSize = 5, Order = 2030, ActivityID = 821, Icon = "UB.tga" },
    ["Slave Pens"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 547, MinLevel = 61, MaxLevel = 69, GroupSize = 5, Order = 2020, ActivityID = 820, Icon = "SP.tga" },
    ["Blood Furnace"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 542, MinLevel = 60, MaxLevel = 68, GroupSize = 5, Order = 2010, ActivityID = 818, Icon = "BF.tga" },
    ["Hellfire Ramparts"] = { Active = true, Expac = "The Burning Crusade", InstanceType = "The Burning Crusade Dungeons",
        InstanceID = 543, MinLevel = 58, MaxLevel = 67, GroupSize = 5, Order = 2000, ActivityID = 817, Icon = "RAMPS.tga" },
    ["Naxxramas"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 533,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 1360, ActivityID = 0, Icon = "NAX.tga" },
    ["Temple of Ahn'Qiraj"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = 531, MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 1350, ActivityID = 843, Icon = "AQ40.tga" },
    ["Blackwing Lair"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 469,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 1340, ActivityID = 840, Icon = "BWL.tga" },
    ["Molten Core"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 409,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 1330, ActivityID = 839, Icon = "MC.tga" },
    ["Onyxia's Lair"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 249,
        MinLevel = 60, MaxLevel = 60, GroupSize = 40, Order = 1320, ActivityID = 838, Icon = "ONY.tga" },
    ["Ruins of Ahn'Qiraj"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = 509, MinLevel = 60, MaxLevel = 60, GroupSize = 20, Order = 1310, ActivityID = 842, Icon = "AQ20.tga" },
    ["Zul'Gurub"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 309,
        MinLevel = 60, MaxLevel = 60, GroupSize = 20, Order = 1300, ActivityID = 836, Icon = "ZG.tga" },
    ["Upper Blackrock Spire"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = 229, MinLevel = 60, MaxLevel = 60, GroupSize = 10, Order = 1290, ActivityID = 837, Icon = "UBRS.tga" },
    ["Dire Maul North"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 429, MinLevel = 56, MaxLevel = 61, GroupSize = 5, Order = 1230, ActivityID = 815, Icon = "DM.tga" },
    ["Dire Maul West"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 429, MinLevel = 56, MaxLevel = 61, GroupSize = 5, Order = 1220, ActivityID = 814, Icon = "DM.tga" },
    ["Scholomance"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 1007,
        MinLevel = 56, MaxLevel = 61, GroupSize = 5, Order = 1210, ActivityID = 797, Icon = "SCHOLO.tga" },
    ["Stratholme"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 329,
        MinLevel = 56, MaxLevel = 61, GroupSize = 5, Order = 1200, ActivityID = 816, Icon = "STRAT.tga" },
    ["Dire Maul East"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 429, MinLevel = 54, MaxLevel = 61, GroupSize = 5, Order = 1190, ActivityID = 813, Icon = "DM.tga" },
    ["Lower Blackrock Spire"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 229, MinLevel = 53, MaxLevel = 61, GroupSize = 5, Order = 1180, ActivityID = 812, Icon = "LBRS.tga" },
    ["Blackrock Depths"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 230, MinLevel = 48, MaxLevel = 60, GroupSize = 5, Order = 1170, ActivityID = 811, Icon = "BRD.tga" },
    ["Sunken Temple"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 109,
        MinLevel = 45, MaxLevel = 54, GroupSize = 5, Order = 1160, ActivityID = 810, Icon = "ST.tga" },
    ["Zul'Farrak"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 209,
        MinLevel = 42, MaxLevel = 50, GroupSize = 5, Order = 1150, ActivityID = 808, Icon = "ZF.tga" },
    ["Maraudon"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 349,
        MinLevel = 40, MaxLevel = 52, GroupSize = 5, Order = 1140, ActivityID = 809, Icon = "MARA.tga" },
    ["Scarlet Cathedral"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 1004, MinLevel = 36, MaxLevel = 44, GroupSize = 5, Order = 1130, ActivityID = 828, Icon = "SM.tga" },
    ["Uldaman"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 70,
        MinLevel = 36, MaxLevel = 44, GroupSize = 5, Order = 1120, ActivityID = 807, Icon = "ULDA.tga" },
    ["Razorfen Downs"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 129, MinLevel = 33, MaxLevel = 41, GroupSize = 5, Order = 1110, ActivityID = 806, Icon = "RFD.tga" },
    ["Scarlet Armory"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 1004, MinLevel = 33, MaxLevel = 41, GroupSize = 5, Order = 1100, ActivityID = 827, Icon = "SM.tga" },
    ["Scarlet Library"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 1004, MinLevel = 31, MaxLevel = 39, GroupSize = 5, Order = 1090, ActivityID = 829, Icon = "SM.tga" },
    ["Scarlet Graveyard"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 1004, MinLevel = 28, MaxLevel = 36, GroupSize = 5, Order = 1080, ActivityID = 805, Icon = "SM.tga" },
    ["Gnomeregan"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 90,
        MinLevel = 24, MaxLevel = 32, GroupSize = 5, Order = 1070, ActivityID = 803, Icon = "GNOMER.tga" },
    ["Razorfen Kraul"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 47,
        MinLevel = 23, MaxLevel = 31, GroupSize = 5, Order = 1060, ActivityID = 804, Icon = "RFK.tga" },
    ["Stormwind Stockades"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 34, MinLevel = 21, MaxLevel = 29, GroupSize = 5, Order = 1050, ActivityID = 802, Icon = "STOCKS.tga" },
    ["Blackfathom Deeps"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 48, MinLevel = 20, MaxLevel = 28, GroupSize = 5, Order = 1040, ActivityID = 801, Icon = "BFD.tga" },
    ["Shadowfang Keep"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 33, MinLevel = 17, MaxLevel = 25, GroupSize = 5, Order = 1030, ActivityID = 800, Icon = "SFK.tga" },
    ["Deadmines"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons", InstanceID = 36,
        MinLevel = 16, MaxLevel = 24, GroupSize = 5, Order = 1020, ActivityID = 799, Icon = "VC.tga" },
    ["Wailing Caverns"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 43, MinLevel = 16, MaxLevel = 24, GroupSize = 5, Order = 1010, ActivityID = 796, Icon = "WC.tga" },
    ["Ragefire Chasm"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Dungeons",
        InstanceID = 389, MinLevel = 13, MaxLevel = 20, GroupSize = 5, Order = 1000, ActivityID = 798, Icon = "RFC.tga" },
}
if WOW_PROJECT_ID == WOW_PROJECT_CLASSIC then
    if C_Seasons and C_Seasons.HasActiveSeason and C_Seasons.HasActiveSeason() then
        if C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
            addon.groupieInstanceData["Blackfathom Deeps"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids",
        InstanceID = 48, MinLevel = 25, MaxLevel = 30, GroupSize = 10, Order = 1040, ActivityID = 801, Icon = "BFD.tga" }
            addon.groupieInstanceData["Gnomeregan"] = { Active = true, Expac = "World of Warcraft", InstanceType = "Classic Raids", InstanceID = 90,
        MinLevel = 40, MaxLevel = 45, GroupSize = 10, Order = 1070, ActivityID = 803, Icon = "GNOMER.tga" }
            addon.instanceVersions = addon.instanceVersions or {}
            addon.instanceVersions["Blackfathom Deeps"] = { { 10, false } }
            addon.instanceVersions["Gnomeregan"] = { { 10, false } }

            addon.instanceConfigData = addon.instanceConfigData or {}
            -- BFD
            addon.instanceConfigData[1040] = addon.instanceConfigData[1040] or {}
            addon.instanceConfigData[1040].InstanceType = "Classic Raids"
            addon.instanceConfigData[1040].MinLevel = 25
            addon.instanceConfigData[1040].MaxLevel = 30
            addon.instanceConfigData[1040].GroupSize = 10
            -- Gnomer
            addon.instanceConfigData[1070] = addon.instanceConfigData[1070] or {}
            addon.instanceConfigData[1070].InstanceType = "Classic Raids"
            addon.instanceConfigData[1070].MinLevel = 40
            addon.instanceConfigData[1070].MaxLevel = 45
            addon.instanceConfigData[1070].GroupSize = 10
        end
    end
end